### ISSUE TITLE
join event doesnt trigger

### ISSUE THREAD

**Issue by yuu2lee4** [ambelovsky/koa-socket-2#1]
when a socket in,it doesnt trigger 'join' event,it only trigger 'connection' event.

**Comment by ambelovsky** [comment]
yuu2lee4,

The 'join' event as specified in the documentation is actually meant to be from a client request in the default namespace to the 'join' endpoint.  For example:

`socket.emit('join', {message: 'test'});`

When the above is sent **from the client application** after connecting, then the 'join' event will fire on the server side.

In this case, the 'join' event has nothing to do with an actual socket connection event.  The 'connection' event is handled automatically behind the scenes in this library, and you are never required to manage this.  

I have updated the documentation to better illustrate this concept using a new example around a 'message' event rather than a 'join' event.  I hope this helps to clear things up.

Thanks!
